---
name: Documents

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  UMLs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install PlantUML
        run: |
          sudo apt update
          sudo apt install -y plantuml

      - name: Make UML diagrams
        run: |
          cd uml/
          make -k -j
